// GENERATED by backend/server.js on startup — do not edit by hand.
// Contains every non-internal IPv4 on the PC (Wi-Fi + Ethernet/LAN).
const generatedLocalApiLanBaseUrls = <String>[
  'http://192.168.1.108:8080',
];
