    <script defer src="/vendor/lucide.js?v=1.24.0"></script>
    <script defer src="/vendor/tabler-icons.js?v=3.44.0"></script>
    <script defer src="/theme.js?v=super-admin-dashboard-gauge-1"></script>
    <script defer src="/square-image-crop.js?v=1080-downscale-1"></script>
    <script defer src="/super_admin_search_states.js?v=super-admin-search-states-4"></script>
    <script defer src="/super_admin.js?v=super-admin-perf-opt-1"></script>
    <script defer src="/admin_biometric_settings.js?v=biometric-snackbar-countdown-js-2"></script>
    <script defer src="/user_data.js?v=super-admin-ai-moderation-summary-1"></script>
    <script defer src="/realtime_sync.js?v=platform-realtime-toggle-1"></script>